# Generated by Django 4.2.11 on 2024-04-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=256)),
                ('hash', models.CharField(max_length=10)),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('api_choice', models.CharField(choices=[('Ad', 'Adf.ly'), ('Bi', 'Bit.ly'), ('Ch', 'Chilp.it'), ('Cl', 'Clck.ru'), ('Cu', 'Cutt.ly'), ('Da', 'Da.gd'), ('Gi', 'Git.io'), ('Is', 'Is.gd'), ('Os', 'Os.db'), ('Ow', 'Ow.ly'), ('Po', 'Po.st'), ('Ti', 'TinyURL.com'), ('Qp', 'Qps.ru')], default='Ti', max_length=2)),
            ],
        ),
    ]
